import { ObjectId } from 'mongodb';

export const productsData = [
	{
		_id: '641e887d05f9ee1717e134a1',
		name: 'Anti-Aging Night Cream',
		desc: 'A rich, restorative night cream that targets fine lines and wrinkles. Formulated with retinol and peptides for smoother, firmer skin.',
		SKU: 'AANC001',
		category_id: '641d424bdbfab7b02ab28b98',
		inventory_id: new ObjectId(),
		price: 55,
		discount_id: null,
		image_url: '/images/anti-aging-night-cream.jpg',
		brand: 'RejuvaSkin',
		size_ml: 50,
		skin_type: ['Mature', 'Dry'],
		key_ingredients: ['Retinol', 'Peptides'],
	},
	{
		_id: '641e887d05f9ee1717e134a2',
		name: 'Vitamin C Serum',
		desc: 'Brightening serum with Vitamin C to reduce dark spots and even skin tone. Antioxidant protection against environmental stressors.',
		SKU: 'VITC001',
		category_id: '641d424bdbfab7b02ab28b91',
		inventory_id: new ObjectId(),
		price: 40,
		discount_id: null,
		image_url: '/images/vitamin-c-serum.jpg',
		brand: 'GlowBoost',
		size_ml: 30,
		skin_type: ['All'],
		key_ingredients: ['Vitamin C', 'Hyaluronic Acid'],
	},
	{
		_id: '641e887d05f9ee1717e134a3',
		name: 'Hydrating Toner',
		desc: 'Alcohol-free toner that replenishes moisture and prepares skin for serum and moisturizer. Infused with rosewater and chamomile.',
		SKU: 'HYDRTONER001',
		category_id: '641d424bdbfab7b02ab28b91',
		inventory_id: new ObjectId(),
		price: 28,
		discount_id: null,
		image_url: '/images/hydrating-toner.jpg',
		brand: 'AquaFresh',
		size_ml: 200,
		skin_type: ['Dry', 'Sensitive'],
		key_ingredients: ['Rosewater', 'Chamomile'],
	},
	{
		_id: '641e887d05f9ee1717e134a4',
		name: 'Exfoliating Cleanser',
		desc: 'Gentle exfoliating cleanser with micro-beads to remove dead skin cells and reveal smoother, brighter skin. Suitable for daily use.',
		SKU: 'EXFOLIATE001',
		category_id: '641d424bdbfab7b02ab28b9a',
		inventory_id: new ObjectId(),
		price: 32,
		discount_id: null,
		image_url: '/images/exfoliating-cleanser.jpg',
		brand: 'SkinRenew',
		size_ml: 150,
		skin_type: ['Normal', 'Oily', 'Combination'],
		key_ingredients: ['Salicylic Acid', 'Jojoba Beads'],
	},
	{
		_id: '641e887d05f9ee1717e134a5',
		name: 'Acne Treatment Gel',
		desc: 'Targeted acne treatment gel with benzoyl peroxide to reduce blemishes and prevent future breakouts. Dries quickly and invisibly.',
		SKU: 'ACNE001',
		category_id: '641d424bdbfab7b02ab28b9a',
		inventory_id: new ObjectId(),
		price: 25,
		discount_id: null,
		image_url: '/images/acne-treatment-gel.jpg',
		brand: 'ClearSkin',
		size_ml: 30,
		skin_type: ['Oily', 'Acne-Prone'],
		key_ingredients: ['Benzoyl Peroxide'],
	},
	{
		_id: '641e887d05f9ee1717e134a6',
		name: 'Lip Balm - Vanilla',
		desc: 'Nourishing lip balm with shea butter and vitamin E to hydrate and protect dry, chapped lips. Delicious vanilla flavor.',
		SKU: 'LIPBALM001',
		category_id: '641d424bdbfab7b02ab28b90',
		inventory_id: new ObjectId(),
		price: 10,
		discount_id: null,
		image_url: '/images/lip-balm.jpg',
		brand: 'Kissable',
		flavor: 'Vanilla',
		key_ingredients: ['Shea Butter', 'Vitamin E'],
	},
	{
		_id: '641e887d05f9ee1717e134a7',
		name: 'Eyelash Growth Serum',
		desc: 'Serum designed to promote longer, thicker eyelashes. Apply nightly for visible results in weeks.',
		SKU: 'EYELASH001',
		category_id: '641d424bdbfab7b02ab28b9c',
		inventory_id: new ObjectId(),
		price: 45,
		discount_id: null,
		image_url: '/images/eyelash-serum.jpg',
		brand: 'LashGrow',
		size_ml: 5,
	},
	{
		_id: '641e887d05f9ee1717e134a8',
		name: 'Brow Gel - Clear',
		desc: 'Clear brow gel to tame and shape eyebrows for a polished look. Long-lasting hold without stiffness.',
		SKU: 'BROWGEL001',
		category_id: '641d424bdbfab7b02ab28b9c',
		inventory_id: new ObjectId(),
		price: 18,
		discount_id: null,
		image_url: '/images/brow-gel.jpg',
		brand: 'BrowDefine',
		color: 'Clear',
		finish: 'Natural',
	},
	{
		_id: '641e887d05f9ee1717e134a9',
		name: 'Eyeshadow Palette - Neutral',
		desc: 'Palette with 12 neutral eyeshadow shades in matte and shimmer finishes. Perfect for creating everyday looks.',
		SKU: 'EYESHADOW001',
		category_id: '641d424bdbfab7b02ab28b9c',
		inventory_id: new ObjectId(),
		price: 35,
		discount_id: null,
		image_url: '/images/eyeshadow-palette.jpg',
		brand: 'ColorGlam',
		shades: ['Beige', 'Brown', 'Taupe', 'Gold'],
		finish: ['Matte', 'Shimmer'],
	},
	{
		_id: '641e887d05f9ee1717e134aa',
		name: 'Concealer - Fair',
		desc: 'Creamy concealer that provides buildable coverage to conceal blemishes, dark circles, and imperfections. Long-wearing formula.',
		SKU: 'CONCEAL001',
		category_id: '641d424bdbfab7b02ab28b9d',
		inventory_id: new ObjectId(),
		price: 22,
		discount_id: null,
		image_url: '/images/concealer.jpg',
		brand: 'CoverUp',
		shade: 'Fair',
		coverage: 'Medium to Full',
	},
	{
		_id: '641e887d05f9ee1717e134ab',
		name: 'Blush - Peach',
		desc: 'Powder blush that adds a natural flush of color to the cheeks. Silky texture and long-lasting wear.',
		SKU: 'BLUSH001',
		category_id: '641d424bdbfab7b02ab28b9d',
		inventory_id: new ObjectId(),
		price: 20,
		discount_id: null,
		image_url: '/images/peach-blush.jpg',
		brand: 'CheekGlow',
		shade: 'Peach',
		finish: 'Matte',
	},
	{
		_id: '641e887d05f9ee1717e134ac',
		name: 'Foundation - Light Beige',
		desc: 'Lightweight foundation that provides buildable coverage and a natural, radiant finish. Blurs imperfections and evens skin tone.',
		SKU: 'FOUND001',
		category_id: '641d424bdbfab7b02ab28b9d',
		inventory_id: new ObjectId(),
		price: 38,
		discount_id: null,
		image_url: '/images/foundation.jpg',
		brand: 'FlawlessBase',
		shade: 'Light Beige',
		coverage: 'Light to Medium',
		finish: 'Radiant',
	},
	{
		_id: '641e887d05f9ee1717e134ad',
		name: 'Setting Powder - Translucent',
		desc: 'Translucent setting powder that sets makeup and controls shine for a long-lasting, matte finish. Blurs pores and imperfections.',
		SKU: 'POWDER001',
		category_id: '641d424bdbfab7b02ab28b9d',
		inventory_id: new ObjectId(),
		price: 25,
		discount_id: null,
		image_url: '/images/setting-powder.jpg',
		brand: 'StayMatte',
		shade: 'Translucent',
		finish: 'Matte',
	},
	{
		_id: '641e887d05f9ee1717e134ae',
		name: 'Mascara - Brown',
		desc: 'Lengthening mascara that defines lashes with a natural brown color.  Smudge-proof and long-lasting formula.',
		SKU: 'MASCBRWN001',
		category_id: '641d424bdbfab7b02ab28b9c',
		inventory_id: new ObjectId(),
		price: 20,
		discount_id: null,
		image_url: '/images/mascara-brown.jpg',
		brand: 'LashPerfect',
		color: 'Brown',
		waterproof: false,
	},
	{
		_id: '641e887d05f9ee1717e134af',
		name: 'Lip Liner - Nude',
		desc: 'Creamy lip liner that defines and shapes lips. Prevents lipstick from feathering and extends wear.',
		SKU: 'LIPLINERND001',
		category_id: '641d424bdbfab7b02ab28b9b',
		inventory_id: new ObjectId(),
		price: 15,
		discount_id: null,
		image_url: '/images/lip-liner-nude.jpg',
		brand: 'LipContour',
		shade: 'Nude',
		formula: 'Creamy',
	},
	{
		_id: '641e887d05f9ee1717e134b0',
		name: 'Highlighter - Champagne',
		desc: 'Powder highlighter that adds a luminous glow to the high points of the face.  Blendable and buildable formula.',
		SKU: 'HIGHLIGHT001',
		category_id: '641d424bdbfab7b02ab28b9d',
		inventory_id: new ObjectId(),
		price: 28,
		discount_id: null,
		image_url: '/images/highlighter-champagne.jpg',
		brand: 'GlowUp',
		shade: 'Champagne',
		finish: 'Shimmer',
	},
	{
		_id: '641e887d05f9ee1717e134b1',
		name: 'Makeup Remover Wipes',
		desc: 'Gentle makeup remover wipes that effectively remove all traces of makeup.  Infused with aloe vera to soothe and hydrate skin.',
		SKU: 'MAKEUPWIPE001',
		category_id: '641d424bdbfab7b02ab28b9a',
		inventory_id: new ObjectId(),
		price: 12,
		discount_id: null,
		image_url: '/images/makeup-wipes.jpg',
		brand: 'CleanSweep',
		count: 25, // Number of wipes
		skin_type: ['All'],
		key_ingredients: ['Aloe Vera'],
	},

	{
		_id: '641e887d05f9ee1717e134b2',
		name: 'Bronzer - Matte',
		desc: 'Powder bronzer that adds warmth and definition to the face.  Matte finish for a natural-looking tan.',
		SKU: 'BRONZER001',
		category_id: '641d424bdbfab7b02ab28b9d',
		inventory_id: new ObjectId(),
		price: 25,
		discount_id: null,
		image_url: '/images/bronzer-matte.jpg',
		brand: 'SunKissed',
		finish: 'Matte',
	},

	{
		_id: '641e887d05f9ee1717e134b3',
		name: 'Body Lotion - Shea Butter',
		desc: 'Rich and moisturizing body lotion with shea butter.  Leaves skin feeling soft, smooth, and hydrated all day long.',
		SKU: 'BODYLOTION001',
		category_id: '641d424bdbfab7b02ab28b9a',
		inventory_id: new ObjectId(),
		price: 18,
		discount_id: null,
		image_url: '/images/body-lotion.jpg',
		brand: 'SilkSkin',
		size_ml: 250,
		key_ingredients: ['Shea Butter', 'Vitamin E'],
	},
	{
		_id: '641e887d05f9ee1717e134b4',
		name: 'Hair Mask - Argan Oil',
		desc: 'Deeply conditioning hair mask with argan oil.  Repairs damaged hair, adds shine, and reduces frizz.',
		SKU: 'HAIRMASK001',
		category_id: '641d424bdbfab7b02ab28b93',
		inventory_id: new ObjectId(),
		price: 22,
		discount_id: null,
		image_url: '/images/hair-mask.jpg',
		brand: 'ShineRepair',
		size_ml: 200,
		key_ingredients: ['Argan Oil'],
	},
	{
		_id: '641e887d05f9ee1717e134b5',
		name: 'Foot Cream - Peppermint',
		desc: 'Soothing foot cream with peppermint oil to refresh and moisturize tired feet.  Helps to soften rough skin.',
		SKU: 'FOOTCREAM001',
		category_id: '641d424bdbfab7b02ab28b94',
		inventory_id: new ObjectId(),
		price: 15,
		discount_id: null,
		image_url: '/images/foot-cream.jpg',
		brand: 'SoleRelief',
		size_ml: 100,
		key_ingredients: ['Peppermint Oil', 'Shea Butter'],
	},

	{
		_id: '641e887d05f9ee1717e134b6',
		name: 'Nail Polish - Red',
		desc: 'High-shine nail polish in a classic red shade.  Long-lasting and chip-resistant formula.',
		SKU: 'NAILPOLISH001',
		category_id: '641d424bdbfab7b02ab28b97',
		inventory_id: new ObjectId(),
		price: 8,
		discount_id: null,
		image_url: '/images/nail-polish.jpg',
		brand: 'ColorGlam',
		color: 'Red',
		finish: 'Glossy',
	},
	{
		_id: '641e887d05f9ee1717e134b7',
		name: 'BB Cream - Medium',
		desc: 'A multi-tasking BB cream that provides medium coverage, evens skin tone, and protects with SPF 30.',
		SKU: 'BBCREAM002',
		category_id: '641d424bdbfab7b02ab28b9d', // Reference to Categories collection (Makeup - Face)
		inventory_id: new ObjectId(),
		price: 40,
		discount_id: null,
		image_url: '/images/bb-cream-medium.jpg',
		brand: 'SkinPerfect',
		shade: 'Medium',
		spf: 30,
	},
	{
		_id: '641e887d05f9ee1717e134b8',
		name: 'Shampoo - Volumizing',
		desc: 'Volumizing shampoo that adds body and thickness to fine hair.  Formulated with biotin and collagen.',
		SKU: 'SHAMPOO001',
		category_id: '641d424bdbfab7b02ab28b9e', // Haircare category
		inventory_id: new ObjectId(),
		price: 16,
		discount_id: null,
		image_url: '/images/volumizing-shampoo.jpg',
		brand: 'VolumeBoost',
		size_ml: 300,
		key_ingredients: ['Biotin', 'Collagen'],
	},
	{
		_id: '641e887d05f9ee1717e134b9',
		name: 'Conditioner - Moisturizing',
		desc: 'Moisturizing conditioner that hydrates and detangles hair.  Leaves hair soft, smooth, and manageable.',
		SKU: 'CONDITIONER001',
		category_id: '641d424bdbfab7b02ab28b9e', // Haircare category
		inventory_id: new ObjectId(),
		price: 16,
		discount_id: null,
		image_url: '/images/moisturizing-conditioner.jpg',
		brand: 'HydrateHair',
		size_ml: 300,
		key_ingredients: ['Argan Oil', 'Shea Butter'],
	},
	{
		_id: '641e887d05f9ee1717e134ba',
		name: 'Perfume - Floral',
		desc: 'A delicate floral perfume with notes of jasmine, rose, and lily of the valley.  Long-lasting fragrance.',
		SKU: 'PERFUME001',
		category_id: '641d424bdbfab7b02ab28b95',
		inventory_id: new ObjectId(),
		price: 60,
		discount_id: null,
		image_url: '/images/floral-perfume.jpg',
		brand: 'BloomScent',
		size_ml: 50,
		scent_notes: ['Jasmine', 'Rose', 'Lily of the Valley'],
	},
	{
		_id: '641e887d05f9ee1717e134bb',
		name: 'Eyeliner Pen - Brown',
		desc: 'A highly pigmented eyeliner pen that allows for precise application in brown. Long-lasting and smudge-proof.',
		SKU: 'EYELINER002',
		category_id: '641d424bdbfab7b02ab28b9c', // Reference to Categories collection (Makeup - Eyes)
		inventory_id: new ObjectId(),
		price: 20,
		discount_id: null,
		image_url: '/images/eyeliner-brown.jpg',
		brand: 'DefineLiner',
		color: 'Brown',
		waterproof: false,
	},
	{
		_id: '641e887d05f9ee1717e134bc',
		name: 'Lipstick - Rose',
		desc: 'A long-lasting, highly pigmented matte lipstick in a Rose shade.  Provides full coverage and comfortable wear.',
		SKU: 'LIPROSE7723AB',
		category_id: '641d424bdbfab7b02ab28b9b', // Reference to Categories collection (Makeup - Lips)
		inventory_id: new ObjectId(), // Create new inventory record
		price: 22,
		discount_id: '641e887d05f9ee1717e13501', // Optional discount reference (Discount ID for 10% off)
		image_url: '/images/rose-lipstick.jpg', // Example image URL
		brand: 'LuxeBeauty',
		shade: 'Rose',
		finish: 'Matte',
	},
];

export default productsData;
